import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Header } from "@/components/Header";
import { SubHeader } from "@/components/SubHeader";
import { Footer } from "@/components/Footer";
import { ProviderManager } from "@/utils/ProviderManager";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ProviderManager>
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
                >
                    <Header />
                    <SubHeader />
                    <main className="p-4 flex-1 mb-8">{children}</main>
                    <Footer />
                </body>
            </ProviderManager>
        </html>
    );
}
